version: 2
defaults:
  working_directory: /tmp
jobs:
  build-job:
    docker:
      - image: circleci/node:chakracore-8.11.1
    steps:
      - run:
        name: Try to install
        command: npm run build
      - persist_to_workspace:
        root: workspace
        paths:
          - dist
  deploy-job:
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
        name: Initialize gcloud
        command: ./deploy.sh
      - run:
        name: list files
        command: ls /tmp/workspace
        
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job
        requires:
          - build-job
        filters:
          branches:
            only: master