version: 2
defaults:
  working_directory: /tmp
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-8.11.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Try to install
          command: npm run build
      - run:
          name: Make build directory
          command: mkdir /tmp/workspace
      - run:
          name: Copy dist to the workspace directory
          command: cp -r dist /tmp/workspace
      - run:
          name: Copy build scripts to workspace
          command: cp -r build /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - dist
            - build
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Initialize gcloud
          command: /tmp/workspace/build/authgcloud.sh
      - run:
          name: list files
          command: ls /tmp/workspace/dist
      - run:
          name: deploy
          command: /tmp/workspace/build/deploy.sh
          # TODO: cache invalidation of bundlejs
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master