version: 2
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-8.11.1
    steps:
      - run:
          name: Try to install
          command: npm run build
      # - persist_to_workspace:
      #     root: workspace
      #     paths:
      #     - dist
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Initialize gcloud
          command: ./deploy.sh
      - run:
          name: list files
          command: ls /tmp/workspace
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master